import React, { useState } from 'react';
import { RoundHeader, Card, SectionTitle, GRAD } from './PracticeComponents';
import { ROUND_RESOURCES } from './RESOURCES';

const TECH_QUESTIONS = {
  DBMS: [
    { q:'What is normalization? Explain 1NF, 2NF, 3NF.', a:'**1NF**: Atomic values, no repeating groups.\n**2NF**: 1NF + no partial dependency (every non-key attribute fully depends on primary key).\n**3NF**: 2NF + no transitive dependency.\n\nExample: Table (OrderID, ProductID, ProductName, CustomerName) — ProductName depends only on ProductID (partial dep). Split into Orders and Products tables.' },
    { q:'Difference between SQL JOIN types.', a:'INNER JOIN: Only matching rows from both tables.\nLEFT JOIN: All left rows + matching right (NULL if no match).\nRIGHT JOIN: All right rows + matching left.\nFULL OUTER JOIN: All rows from both tables.\nCROSS JOIN: Cartesian product — every combination.\nSELF JOIN: Table joined with itself (e.g., employee-manager hierarchy).' },
    { q:'What are ACID properties?', a:'Atomicity: All or nothing — full commit or full rollback.\nConsistency: DB moves between valid states only.\nIsolation: Concurrent transactions do not interfere.\nDurability: Committed data persists even after crash.\n\nACID is guaranteed by the transaction manager using logging (WAL — Write-Ahead Logging) and locking.' },
    { q:'Explain indexing in databases. Types?', a:'An index is a data structure (B-Tree or Hash) for fast row lookup without full table scan.\n\nTypes:\n- Primary: auto-created on primary key\n- Unique: no duplicate values allowed\n- Composite: multiple columns together\n- Clustered: physically reorders table data (one per table)\n- Non-clustered: separate structure pointing to data\n- Full-text: for LIKE/text search queries\n\nTradeoff: Speeds up SELECT; slows INSERT/UPDATE/DELETE.' },
    { q:'What are transactions and deadlocks?', a:'Transaction: A logical unit of work (BEGIN → operations → COMMIT/ROLLBACK).\n\nDeadlock: T1 waits for T2\'s lock; T2 waits for T1\'s lock → neither can proceed.\n\nPrevention: Lock ordering (always acquire locks in same order), timeout-based rollback.\nDetection: Wait-for graph — if cycle found → rollback the youngest transaction.' },
    { q:'What is a view? Materialized view vs. regular view?', a:'View: A virtual table defined by a stored SQL query. Does not store data itself.\n\nRegular View: Recomputed on every access. Always shows fresh data. No storage.\nMaterialized View: Physically stores query result. Refreshed periodically or on demand. Much faster for expensive queries.\n\nUse views for security (hiding columns), simplifying complex queries, logical abstraction.' },
    { q:'Stored Procedures vs. Functions', a:'Stored Procedure:\n- Can return 0 or multiple values via OUT parameters\n- Can use DML (INSERT/UPDATE/DELETE) inside\n- Called with EXECUTE/CALL\n- Can have side effects\n\nFunction:\n- Must return exactly one value\n- Cannot use DML statements (in most DBs)\n- Can be used directly in SELECT/WHERE clauses\n- No side effects (pure)\n\nUse procedures for complex business logic; functions for computed values.' },
    { q:'WHERE vs. HAVING — what is the difference?', a:'WHERE: Filters rows BEFORE aggregation. Works on individual row data.\nHAVING: Filters groups AFTER GROUP BY. Works on aggregated data.\n\nExample:\nSELECT dept, COUNT(*) FROM emp WHERE salary > 50000 GROUP BY dept;  -- WHERE filters rows first\nSELECT dept, COUNT(*) FROM emp GROUP BY dept HAVING COUNT(*) > 5;   -- HAVING filters groups\n\nRule: Non-aggregate filter → WHERE. Aggregate filter (COUNT/SUM/AVG) → HAVING.' },
    { q:'What is database sharding?', a:'Sharding: Horizontal partitioning of data across multiple database servers (shards). Each shard holds a subset of data.\n\nStrategies:\n- Range-based: shard by ID range (1–1M on shard1, etc.)\n- Hash-based: shard_id = hash(user_id) % num_shards\n- Geographic: data stored near users\n\nPros: Horizontal scalability, reduced load per server.\nCons: Complex joins across shards, hotspot issues, resharding difficulty.' },
    { q:'Explain CAP theorem.', a:'CAP Theorem (Brewer, 2000): A distributed system can guarantee at most 2 of 3:\n\nConsistency: Every read gets the most recent write.\nAvailability: Every request receives a response (may not be latest data).\nPartition Tolerance: System works despite network partitions.\n\nSince network partitions are inevitable, the real choice is CP vs AP:\n- CP systems: MongoDB, HBase, ZooKeeper (prioritize consistency)\n- AP systems: Cassandra, CouchDB, DynamoDB (prioritize availability)' },
  ],
  OS: [
    { q:'Process vs. Thread — differences?', a:'Process: Independent execution unit with its own memory (code, heap, stack, data).\nThread: Lightweight unit within a process sharing its memory space.\n\nDifferences:\n- Memory: Process has isolated memory; threads share heap/data\n- Creation: Thread creation ~10x faster than process\n- Communication: Threads use shared memory; processes use IPC\n- Failure: Thread crash can kill process; process crash is isolated\n- Context switch: Thread switch faster (no memory map change)' },
    { q:'What is deadlock? Four necessary conditions?', a:'Deadlock: Two or more processes permanently blocked, each waiting for resources held by another.\n\nFour Necessary Conditions (Coffman):\n1. Mutual Exclusion: Resource held by only one process at a time\n2. Hold and Wait: Process holds resource while waiting for another\n3. No Preemption: Resources cannot be forcibly taken\n4. Circular Wait: P1→P2→P3→P1 chain\n\nPrevention: Break any one condition (resource ordering breaks circular wait).' },
    { q:'CPU Scheduling algorithms — explain all types.', a:'FCFS (First Come First Serve): Non-preemptive, simple, causes convoy effect.\nSJF (Shortest Job First): Optimal avg waiting time; may starve long processes.\nSRTF (Shortest Remaining Time First): Preemptive SJF.\nRound Robin: Fixed time quantum; fair, good response time for time-sharing.\nPriority Scheduling: Higher priority first; starvation solved by aging.\nMFQ (Multilevel Feedback Queue): Multiple queues; processes move between queues based on behavior.\n\nKey metrics: Waiting time, Turnaround time = Burst + Waiting, Response time.' },
    { q:'What is virtual memory and paging?', a:'Virtual Memory: Illusion of large memory using disk as extension of RAM.\n\nPaging: Divides virtual address space into pages (fixed size, e.g., 4KB). Physical RAM divided into frames. OS maintains page tables for mapping.\n\nPage Fault: Referenced page not in RAM → OS loads from disk (~1ms vs ~100ns for RAM).\n\nTLB (Translation Lookaside Buffer): Cache for page table entries (speeds up address translation 10-100x).\n\nThrashing: Too many page faults → OS spends more time paging than executing. Fix: reduce multiprogramming degree.' },
    { q:'What is a semaphore? Mutex vs. Semaphore?', a:'Semaphore: Integer variable for process synchronization. Operations: wait(P) decrements, signal(V) increments.\n- Binary semaphore: 0 or 1\n- Counting semaphore: Any non-negative value (resource counting)\n\nMutex: Mutual exclusion lock. Only the thread that locked it can unlock it.\n\nDifferences:\n- Ownership: Mutex has ownership (only locker can unlock); semaphore does not\n- Purpose: Mutex for mutual exclusion; semaphore for signaling/counting\n- Value: Mutex is binary; semaphore can be any count\n- Use: Mutex for shared resource protection; semaphore for producer-consumer' },
    { q:'What are system calls? Give examples.', a:'System calls: Interface between user programs and OS kernel. Transition from user mode to kernel mode.\n\nCategories:\n- Process control: fork(), exec(), wait(), exit(), kill()\n- File management: open(), read(), write(), close(), seek(), stat()\n- Device management: ioctl(), read(), write()\n- Information: getpid(), time(), gettimeofday()\n- Communication: pipe(), socket(), send(), recv(), shmget()\n\nHow it works: User code → library wrapper → software interrupt/trap → kernel mode → executes → returns to user mode.' },
    { q:'Explain memory management — fragmentation types.', a:'Internal Fragmentation: Wasted space within an allocated partition (fixed-size partitions).\nExternal Fragmentation: Enough total free space but not contiguous (dynamic allocation).\n\nSolutions:\n- Compaction: Move allocated memory to create contiguous free space (expensive)\n- Paging: Fixed-size pages eliminate external fragmentation\n- Segmentation: Variable-size segments (external fragmentation possible)\n\nMemory allocation algorithms: First Fit (fast), Best Fit (least waste but slow), Worst Fit (largest free block).' },
    { q:'What is inter-process communication (IPC)?', a:'IPC: Mechanisms for processes to exchange data.\n\n1. Pipes: Unidirectional byte stream. Anonymous (parent-child) or named (FIFO, unrelated processes).\n2. Message Queues: Messages stored in kernel queue. Asynchronous communication.\n3. Shared Memory: Fastest IPC — processes map same physical memory. Needs synchronization.\n4. Sockets: Network communication (or local via Unix domain sockets).\n5. Signals: Async notifications — SIGKILL, SIGTERM, SIGINT.\n6. Semaphores: Synchronization only (not data transfer).\n\nChoosing: Shared memory for speed; sockets for network; pipes for streaming data.' },
  ],
  CN: [
    { q:'Explain the OSI model — all 7 layers.', a:'Layer 7 - Application: HTTP, FTP, SMTP, DNS, DHCP. User-facing protocols.\nLayer 6 - Presentation: Encryption (TLS), compression, data format (JPEG, ASCII, UTF-8).\nLayer 5 - Session: Session management, authentication (NetBIOS, RPC).\nLayer 4 - Transport: TCP (reliable), UDP (fast). Ports, segmentation, flow control.\nLayer 3 - Network: IP, ICMP, routing, logical addressing. Routers operate here.\nLayer 2 - Data Link: Ethernet, MAC addressing, ARP, error detection (CRC). Switches.\nLayer 1 - Physical: Bits on wire — cables, fiber, radio, voltage levels.\n\nMnemonic: "All People Seem To Need Data Processing"' },
    { q:'TCP vs. UDP — when to use each?', a:'TCP (Transmission Control Protocol):\n- Connection-oriented: 3-way handshake (SYN→SYN-ACK→ACK)\n- Reliable: sequence numbers, ACKs, retransmission\n- Flow control: sliding window; Congestion control: slow start, AIMD\n- Use: HTTP/HTTPS, FTP, SSH, email, banking\n\nUDP (User Datagram Protocol):\n- Connectionless, no handshake\n- No reliability guarantees\n- Lower latency, minimal overhead\n- Use: DNS, video streaming, VoIP, gaming, live broadcast\n\nWhen UDP wins: When speed matters more than reliability and some packet loss is acceptable.' },
    { q:'What happens when you type a URL in a browser?', a:'1. DNS Resolution: browser cache → OS cache → recursive resolver → root NS → TLD NS → authoritative NS → IP address\n2. TCP Connection: 3-way handshake with server IP on port 80/443\n3. TLS Handshake (HTTPS): Certificate exchange, key agreement (ECDHE), session key established\n4. HTTP Request: GET / HTTP/1.1 with headers (Host, Cookie, Accept-Encoding)\n5. Server Processing: Web server → app logic → database → response\n6. HTTP Response: 200 OK, HTML content, caching headers\n7. Rendering: Parse HTML → DOM → fetch CSS/JS → CSSOM → Render tree → Layout → Paint\n8. Subsequent requests: HTTP/2 multiplexing for parallel asset loading' },
    { q:'What is subnetting? How do you calculate?', a:'Subnetting: Dividing a network into smaller sub-networks to reduce broadcast domains and improve security.\n\nExample: Split 192.168.1.0/24 into 4 subnets:\n- Use /26 (borrow 2 bits): 4 subnets, 64 IPs each (62 usable)\n- Subnet 1: 192.168.1.0/26  (hosts: .1 to .62, broadcast: .63)\n- Subnet 2: 192.168.1.64/26 (hosts: .65 to .126, broadcast: .127)\n- Subnet 3: 192.168.1.128/26\n- Subnet 4: 192.168.1.192/26\n\nFormulas: Subnets = 2^n (n=borrowed bits). Usable hosts = 2^h - 2 (h=host bits).' },
    { q:'Explain HTTP vs HTTPS. How does TLS work?', a:'HTTP: Plain text protocol, port 80. Vulnerable to eavesdropping and MITM attacks.\nHTTPS: HTTP over TLS, port 443. Encrypted, authenticated, integrity-protected.\n\nTLS Handshake:\n1. Client Hello: TLS version, cipher suites supported, random nonce\n2. Server Hello: Chosen cipher, server certificate (with public key)\n3. Client verifies certificate against trusted CA chain\n4. Key Exchange: ECDHE — both derive same shared secret mathematically\n5. Session keys derived from shared secret + both nonces\n6. Application data encrypted with symmetric keys\n\nTLS 1.3 improvements: Fewer round trips (1-RTT), mandatory forward secrecy, removed weak ciphers.' },
    { q:'What is DNS? Record types explained.', a:'DNS (Domain Name System): Distributed hierarchical database translating domain names to IP addresses.\n\nRecord types:\n- A: Domain → IPv4 address (example.com → 93.184.216.34)\n- AAAA: Domain → IPv6 address\n- CNAME: Canonical name alias (www → example.com)\n- MX: Mail exchange server for the domain\n- NS: Authoritative nameservers for domain\n- TXT: Text data (SPF, DKIM, domain verification)\n- PTR: Reverse DNS (IP → domain)\n- SOA: Start of Authority (zone metadata)\n\nTTL: Time to live — how long to cache the record. Lower = more frequent lookups, higher = less flexibility.' },
    { q:'Hub vs. Switch vs. Router — differences?', a:'Hub (Layer 1): Broadcasts all traffic to all ports. Creates one large collision domain. Obsolete.\n\nSwitch (Layer 2): Uses MAC address table to forward frames only to destination port. Creates separate collision domains. Operates at LAN level.\n\nRouter (Layer 3): Routes packets between different networks using IP addresses. Connects LANs to WANs/internet. Provides NAT, firewall, DHCP.\n\nGateway: Connects networks with different protocols (may do protocol translation at application level).\n\nLayer 3 Switch: Switch with some routing capability. Used in large internal networks.' },
    { q:'What is NAT and why is it used?', a:'NAT (Network Address Translation): Maps private IP addresses to public IP addresses and vice versa.\n\nWhy needed: IPv4 only has 4.3 billion addresses. NAT allows many private devices to share one public IP.\n\nTypes:\n- SNAT (Source NAT): Change source IP — outbound traffic from private network\n- DNAT (Destination NAT): Change destination IP — port forwarding\n- PAT (Port Address Translation): Multiple private IPs share one public IP using different ports (most common)\n\nBenefits: IPv4 address conservation, hides internal network structure, acts as basic firewall.\nDownside: Breaks end-to-end connectivity, complicates P2P, requires stateful tracking.' },
  ],
  OOPs: [
    { q:'Explain the four pillars of OOP.', a:'Encapsulation: Bundle data + methods together. Hide internals via private fields + public getters/setters. Reduces coupling, protects data integrity.\n\nAbstraction: Expose only what is necessary. Hide implementation details behind interfaces and abstract classes.\n\nInheritance: Child class inherits parent properties and methods. Promotes code reuse. Types: single, multilevel, hierarchical, multiple (via interfaces in Java).\n\nPolymorphism:\n- Compile-time (static): Method overloading (same name, different params)\n- Runtime (dynamic): Method overriding (same signature, different implementation in subclass; resolved via vtable)' },
    { q:'Abstract class vs. Interface — when to use each?', a:'Abstract Class:\n- Can have abstract + concrete methods\n- Can have instance variables, constructors\n- Single inheritance only (Java/C#)\n- Use for "is-a" relationship with shared state/behavior\n- Example: Shape (abstract with area()) → Circle, Rectangle\n\nInterface:\n- All abstract by default (Java 8+: default/static methods allowed)\n- No instance variables (only public static final constants)\n- A class can implement multiple interfaces\n- Use for "can-do" capability contracts\n- Example: Flyable, Serializable, Comparable\n\nRule: Sharing code → abstract class. Defining capability → interface.' },
    { q:'Explain SOLID principles with examples.', a:'S - Single Responsibility: One class, one reason to change. UserAuthService does auth only; UserEmailService handles email.\n\nO - Open/Closed: Open for extension, closed for modification. Add new shape types without modifying area calculator — use polymorphism.\n\nL - Liskov Substitution: Subclasses must be substitutable for parent. Square extending Rectangle violates this (setWidth behavior differs).\n\nI - Interface Segregation: Many small interfaces > one fat interface. Printer should not be forced to implement fax().\n\nD - Dependency Inversion: Depend on abstractions, not concretions. Inject IDatabase interface, not MySQLDatabase class.' },
    { q:'What are design patterns? Explain 5 important ones.', a:'Design patterns: Reusable solutions to common software design problems.\n\nCreational:\n- Singleton: One instance globally (DB connection pool, config). Risk: global state, hard to test.\n- Factory Method: Create objects without specifying exact class. Useful when creation logic is complex.\n- Builder: Construct complex objects step by step (e.g., StringBuilder, query builders).\n\nStructural:\n- Adapter: Make incompatible interfaces work together. Wrap legacy API to match new interface.\n- Decorator: Add behavior to objects dynamically without subclassing (e.g., Java I/O streams).\n\nBehavioral:\n- Observer: Publish-subscribe. One object notifies many. Used in event systems, MVC, UI frameworks.\n- Strategy: Interchangeable algorithms at runtime. E.g., different sorting or payment strategies.' },
    { q:'Method overloading vs. overriding?', a:'Overloading (Compile-time polymorphism):\n- Same class, same method name, different parameters (type/count)\n- Return type alone does NOT differentiate\n- Resolved at compile time by the compiler\nvoid print(int x) {} and void print(String s) {}  // Overloaded\n\nOverriding (Runtime polymorphism):\n- Subclass provides specific implementation for parent method\n- Same signature (name + params + return type)\n- @Override annotation in Java (compiler validates)\n- Resolved at runtime via vtable/dynamic dispatch\nclass Dog extends Animal { @Override void sound() { print("Woof"); } }' },
    { q:'Composition vs. Inheritance — which to prefer?', a:'Inheritance ("is-a"): Child class inherits parent behavior. Tight coupling.\nclass Dog extends Animal {}  // Dog IS AN Animal\n\nComposition ("has-a"): Class contains instance of another class. Loose coupling.\nclass Car { private Engine engine; }  // Car HAS AN Engine\n\nPrefer Composition over Inheritance (GoF principle):\n- More flexible at runtime (swap components)\n- Avoids fragile base class problem\n- Easier to test (mock dependencies)\n- No deep, brittle inheritance hierarchies\n\nUse inheritance: Only for genuine is-a relationships where behavior truly needs to be inherited.' },
    { q:'What is the difference between == and .equals() in Java?', a:'== operator: Compares references (memory addresses) for objects. For primitives, compares values.\n\n.equals(): Compares content/logical equality. Default Object.equals() compares references. Override to compare field values.\n\nString str1 = new String("hello");\nString str2 = new String("hello");\nstr1 == str2      // false (different objects in heap)\nstr1.equals(str2) // true (same content)\n\nString Pool: String literals share pool.\nString s1 = "hello"; String s2 = "hello";\ns1 == s2 // true (both reference pool object)\n\nRule: Always use .equals() for object comparison. Never use == for Strings.' },
    { q:'What is Exception Handling? Checked vs. Unchecked?', a:'Exception: Event that disrupts normal program flow. Java uses try-catch-finally.\n\ntry { risky code }\ncatch (IOException e) { handle }\nfinally { always runs — close resources }\n\nChecked Exceptions:\n- Must be declared (throws) or caught at compile time\n- Extend Exception but not RuntimeException\n- Examples: IOException, SQLException, ClassNotFoundException\n- Forces caller to handle or propagate\n\nUnchecked Exceptions (RuntimeException):\n- Not required to be caught or declared\n- Examples: NullPointerException, ArrayIndexOutOfBoundsException, IllegalArgumentException\n- Usually indicate programming bugs\n\ntry-with-resources: Auto-closes resources (Java 7+). Eliminates finally block for cleanup.' },
  ],
  Java: [
    { q:'What is the difference between JDK, JRE, and JVM?', a:'JVM (Java Virtual Machine): Executes Java bytecode. Platform-specific implementation. Provides garbage collection, JIT compilation.\n\nJRE (Java Runtime Environment): JVM + runtime libraries (java.lang, java.util, etc.). Used to RUN Java applications.\n\nJDK (Java Development Kit): JRE + development tools (javac compiler, debugger, javadoc, jar). Used to DEVELOP Java applications.\n\nCompilation flow: .java source → javac compiler → .class bytecode → JVM → JIT → native machine code.\n\nWrite Once, Run Anywhere: Bytecode is platform-independent; JVM is platform-specific.' },
    { q:'Explain garbage collection in Java.', a:'GC: Automatic memory management — reclaims memory of unreachable objects.\n\nHeap structure:\n- Young Generation: Eden + Survivor spaces (S0, S1). Minor GC runs frequently (fast).\n- Old Generation (Tenured): Long-lived objects. Major/Full GC (slow, stop-the-world).\n- Metaspace (Java 8+): Class metadata. Replaced PermGen.\n\nGC Algorithms:\n- Serial GC: Single-threaded, small apps\n- Parallel GC: Multi-threaded, throughput focus\n- G1 GC (default Java 9+): Region-based, predictable pause times\n- ZGC/Shenandoah: Ultra-low-latency (<10ms pauses), Java 15+\n\nfinalize(): Deprecated. Use try-with-resources and AutoCloseable instead.' },
    { q:'ArrayList vs. LinkedList — which to use when?', a:'ArrayList:\n- Backed by dynamic array\n- O(1) random access (get by index)\n- O(n) insert/delete in middle (shifts elements)\n- Better cache performance (contiguous memory)\n- Use when: frequent reads, rare middle inserts\n\nLinkedList:\n- Doubly-linked nodes\n- O(n) random access (must traverse)\n- O(1) insert/delete at head/tail\n- More memory overhead (prev/next pointers per node)\n- Implements Deque — use as queue or stack\n- Use when: frequent head/tail inserts, implementing queue\n\nPractice: ArrayList is usually preferred. LinkedList rarely wins on modern hardware due to cache misses.' },
    { q:'What are Java 8+ major features?', a:'Lambda Expressions: Anonymous functions for cleaner code.\nlist.forEach(x -> System.out.println(x));\n\nStream API: Functional-style data processing (filter, map, reduce, collect).\nlist.stream().filter(x -> x > 0).map(x -> x*2).collect(Collectors.toList());\n\nOptional<T>: Avoid NullPointerException.\nOptional.ofNullable(value).orElse("default");\n\nDefault methods in interfaces: Add methods without breaking existing implementations.\n\nMethod references: list.forEach(System.out::println)\n\nDate/Time API: java.time — LocalDate, LocalDateTime, ZonedDateTime (replaces buggy Date/Calendar).\n\nJava 9+: Modules, var (Java 10), Records (Java 16), Sealed classes (Java 17), Pattern matching (Java 21).' },
    { q:'Explain HashMap internals and thread safety.', a:'HashMap: Key-Value store using hash table. O(1) average get/put.\n\nInternals (Java 8+):\n- Array of buckets (default 16)\n- Each bucket: linked list; converts to Red-Black tree when 8+ entries\n- hashCode() → compress to bucket index\n- Collision: multiple keys in same bucket\n\nhashCode() contract: Equal objects MUST have equal hash codes. Override both equals() and hashCode() together.\n\nLoad factor: Default 0.75. When size > capacity × 0.75 → resize (double, rehash all).\n\nThread safety:\n- HashMap: NOT thread-safe\n- Collections.synchronizedMap(): Thread-safe but coarse lock\n- ConcurrentHashMap: Thread-safe with segment-level locking (Java 8: node-level). Preferred for concurrent access.' },
    { q:'What is multithreading in Java? Thread vs. Runnable?', a:'Multithreading: Running multiple threads concurrently for parallel/concurrent execution.\n\nCreating threads:\n1. Extend Thread class: class MyThread extends Thread { public void run() {...} }\n2. Implement Runnable: class Task implements Runnable { public void run() {...} }\n   new Thread(new Task()).start();\n3. Callable + Future: Returns result, can throw checked exceptions.\n4. ExecutorService: Thread pool management (Executors.newFixedThreadPool(n)).\n\nPrefer Runnable/Callable over extending Thread:\n- Can still extend other classes\n- Better separation of task and execution\n\nSynchronization: synchronized keyword, ReentrantLock, volatile for visibility.' },
    { q:'What is the Collections framework hierarchy?', a:'Iterable → Collection\n  ├── List (ordered, duplicates)\n  │   ├── ArrayList\n  │   ├── LinkedList\n  │   └── Vector (synchronized, legacy)\n  ├── Set (no duplicates)\n  │   ├── HashSet (unordered, O(1))\n  │   ├── LinkedHashSet (insertion order)\n  │   └── TreeSet (sorted, O(log n))\n  └── Queue\n      ├── LinkedList (also Queue)\n      ├── PriorityQueue (min-heap)\n      └── ArrayDeque (efficient Deque)\n\nMap (key-value, NOT Collection)\n  ├── HashMap (unordered, O(1))\n  ├── LinkedHashMap (insertion order)\n  ├── TreeMap (sorted by key, O(log n))\n  └── ConcurrentHashMap (thread-safe)' },
    { q:'Explain String, StringBuilder, StringBuffer.', a:'String: Immutable. Every modification creates a new String object. Stored in String Pool.\nGood for: Constant/fixed strings, use as HashMap keys.\n\nStringBuilder: Mutable, NOT thread-safe. Use in single-threaded contexts.\nFastest for string concatenation in loops.\nstringBuilder.append("hello").append(" world");\n\nStringBuffer: Mutable, thread-safe (synchronized methods). Slower than StringBuilder.\nUse only when multiple threads access same buffer.\n\nPerformance: String concatenation in loop creates O(n²) objects.\nAlways use StringBuilder.append() in loops.\n\nJava 8+: String.join(), String.format(), String.chars() (IntStream).' },
  ],
  Python: [
    { q:'Python GIL — what is it and how does it affect concurrency?', a:'GIL (Global Interpreter Lock): Mutex allowing only one thread to execute Python bytecode at a time.\n\nImpact:\n- CPU-bound multi-threading: GIL prevents true parallelism → no speedup from threads\n- I/O-bound multi-threading: GIL released during I/O → threads work well\n\nSolutions:\n- multiprocessing: Separate processes, each with own GIL → true CPU parallelism\n- asyncio: Event loop for I/O-bound concurrency (cooperative multitasking)\n- C extensions: NumPy, Cython release GIL for computation\n- PyPy/Jython: Alternative Python implementations (no GIL)\n\nRule: Threads for I/O-bound (HTTP requests, file I/O); multiprocessing for CPU-bound (data processing).' },
    { q:'List, Tuple, Set, Dict — differences and use cases.', a:'List [1,2,3]: Ordered, mutable, allows duplicates. Use for sequences that change.\nAccess: O(1) by index. Search: O(n).\n\nTuple (1,2,3): Ordered, immutable, allows duplicates. Use for fixed data, dict keys, function returns.\nSlightly faster than list. Hashable if contents are hashable.\n\nSet {1,2,3}: Unordered, mutable, NO duplicates. O(1) average lookup, add, remove.\nUse for unique collections, membership tests, set operations (union, intersection, difference).\n\nDict {k:v}: Key-value pairs, ordered (Python 3.7+), mutable, unique keys. O(1) average lookup.\nUse for mapping, caching, counting (Counter), grouping data.' },
    { q:'What are decorators in Python? Write a custom one.', a:'Decorator: A function that wraps another function to extend its behavior without modifying it.\n\nimport time\ndef timer(func):\n    def wrapper(*args, **kwargs):\n        start = time.time()\n        result = func(*args, **kwargs)\n        print(f"Time: {time.time()-start:.3f}s")\n        return result\n    return wrapper\n\n@timer\ndef slow_function():\n    time.sleep(1)\n\nBuilt-in decorators:\n@property: Getter/setter syntax for class attributes\n@staticmethod: Method that does not receive self or cls\n@classmethod: Method that receives cls (class reference)\n@abstractmethod: Forces subclasses to implement method\n@lru_cache: Memoization from functools\n\nUse cases: Logging, timing, auth, caching, input validation, retry logic.' },
    { q:'Generators and iterators — explain with examples.', a:'Iterator: Object implementing __iter__() and __next__(). Raises StopIteration when exhausted.\n\nGenerator: Function using yield. Creates iterator automatically. Lazy evaluation — values generated on demand.\n\ndef fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a         # suspends function, returns value\n        a, b = b, a+b  # resumes on next()\n\nfib = fibonacci()\nprint(next(fib))  # 0\nprint(next(fib))  # 1\n\nGenerator expression (lazy): (x**2 for x in range(10000))  # O(1) memory\nList comprehension (eager): [x**2 for x in range(10000)]   # O(n) memory\n\nUse generators for: large datasets, infinite sequences, pipeline data processing.' },
    { q:'What is *args and **kwargs?', a:'*args: Allows function to accept any number of positional arguments. Received as tuple.\n\n**kwargs: Allows function to accept any number of keyword arguments. Received as dict.\n\ndef log(*args, **kwargs):\n    print(args)    # (1, "hello", True)\n    print(kwargs)  # {"level": "INFO", "timestamp": 123}\n\nlog(1, "hello", True, level="INFO", timestamp=123)\n\nUnpacking:\nmy_list = [1, 2, 3]\nfunc(*my_list)      # unpacks list as positional args\n\nmy_dict = {"a": 1, "b": 2}\nfunc(**my_dict)     # unpacks dict as keyword args\n\nOrdering in function signature: def f(a, b, *args, key=val, **kwargs)' },
    { q:'What are Python comprehensions?', a:'List comprehension: [expression for item in iterable if condition]\nsquares = [x**2 for x in range(10) if x % 2 == 0]  # [0, 4, 16, 36, 64]\n\nDict comprehension: {k: v for k, v in pairs}\nword_len = {word: len(word) for word in ["hello", "world"]}  # {"hello": 5, "world": 5}\n\nSet comprehension: {expression for item in iterable}\nunique_lengths = {len(word) for word in ["cat", "dog", "elephant"]}  # {3, 8}\n\nGenerator expression (lazy): (x**2 for x in range(10))\n\nNested: matrix = [[row[i] for row in matrix] for i in range(len(matrix[0]))]  # transpose\n\nBenefits: More Pythonic, faster than loops (C-level iteration), readable for simple transformations.' },
    { q:'What is Python\'s memory management?', a:'Python uses reference counting as primary GC mechanism.\n\nReference counting: Object destroyed when reference count drops to 0.\nimport sys; sys.getrefcount(obj)  # check reference count\n\nCyclic GC: Handles circular references that ref counting cannot collect.\nGenerational: Three generations (0, 1, 2). Newer objects collected more frequently.\n\nMemory pools: Python pre-allocates memory in pools for small objects (<512 bytes) via pymalloc. Avoids OS malloc overhead.\n\nInternment: Small integers (-5 to 256) and short strings are interned (shared in memory pool).\na = 256; b = 256; a is b  # True (same object)\na = 257; b = 257; a is b  # False (different objects)\n\ngc module: import gc; gc.collect() forces GC cycle.' },
  ],
  DSA: [
    { q:'BFS vs. DFS — differences and use cases.', a:'BFS (Breadth-First Search):\n- Uses Queue, explores level by level\n- O(V+E) time, O(V) space\n- Finds shortest path in UNWEIGHTED graph\n- Use: shortest path, nearest neighbor, level-order, connected components, bipartite check\n\nDFS (Depth-First Search):\n- Uses Stack/recursion, explores as deep as possible\n- O(V+E) time, O(V) space (recursion stack)\n- Use: cycle detection, topological sort, maze solving, path existence, SCC\n\nWhen BFS: Shortest path, level processing\nWhen DFS: Cycle detection, topological sort, exhaustive search\n\nTopological Sort: DFS-based ordering of DAG. Kahn\'s algorithm uses BFS (in-degree based).' },
    { q:'Explain Dynamic Programming — approaches and classic problems.', a:'DP: Solve complex problems by breaking into overlapping subproblems and storing results.\n\nTop-down (Memoization): Recursive + cache. Natural to implement.\nmemo = {}\ndef fib(n):\n    if n <= 1: return n\n    if n in memo: return memo[n]\n    memo[n] = fib(n-1) + fib(n-2)\n    return memo[n]\n\nBottom-up (Tabulation): Iterative, fill table from base cases. Better space.\ndp = [0] * (n+1)\ndp[1] = 1\nfor i in range(2, n+1): dp[i] = dp[i-1] + dp[i-2]\n\nClassic problems: Fibonacci, 0/1 Knapsack, LCS (Longest Common Subsequence), LIS, Coin Change, Edit Distance, Matrix Chain Multiplication, Rod Cutting.' },
    { q:'Sorting algorithms — complexity table.', a:'Algorithm     | Best       | Average    | Worst      | Space  | Stable\nBubble Sort   | O(n)       | O(n²)      | O(n²)      | O(1)   | Yes\nSelection Sort| O(n²)      | O(n²)      | O(n²)      | O(1)   | No\nInsertion Sort| O(n)       | O(n²)      | O(n²)      | O(1)   | Yes\nMerge Sort    | O(n log n) | O(n log n) | O(n log n) | O(n)   | Yes\nQuick Sort    | O(n log n) | O(n log n) | O(n²)      | O(logn)| No\nHeap Sort     | O(n log n) | O(n log n) | O(n log n) | O(1)   | No\nCounting Sort | O(n+k)     | O(n+k)     | O(n+k)     | O(k)   | Yes\nRadix Sort    | O(nk)      | O(nk)      | O(nk)      | O(n+k) | Yes\n\nBest in practice: QuickSort (cache-friendly), MergeSort (stable, external), TimSort (Python/Java default = Merge+Insertion).' },
    { q:'HashMap internals — how does hashing work?', a:'HashMap: Key-Value store using hash table for O(1) average operations.\n\nInternals (Java 8+):\n- Array of buckets (default 16)\n- Each bucket: linked list, converts to Red-Black tree when 8+ entries\n\nput() process:\n1. key.hashCode() → compress to bucket index: idx = hashCode & (capacity-1)\n2. If bucket empty → insert node\n3. If collision → check key equality; update if same key, else add to chain\n\nCollision resolution: Chaining (linked list/tree)\n\nLoad factor: 0.75 default. Resize at 75% capacity → double size, rehash all.\n\nKey requirements: Override both equals() AND hashCode() consistently.\nContract: a.equals(b) → a.hashCode() == b.hashCode()' },
    { q:'Tree traversals — in-order, pre-order, post-order, level-order.', a:'For BST: 4(root), left: 2(1,3), right: 6(5,7)\n\nIn-order (Left→Root→Right): 1,2,3,4,5,6,7 — SORTED for BST! Use: print BST sorted.\nPre-order (Root→Left→Right): 4,2,1,3,6,5,7 — Use: copy/serialize tree, expression trees.\nPost-order (Left→Right→Root): 1,3,2,5,7,6,4 — Use: delete tree, evaluate expression trees.\nLevel-order (BFS): 4,2,6,1,3,5,7 — Use: level processing, shortest path in tree.\n\nAll traversals: O(n) time, O(h) space (h = height; O(log n) balanced, O(n) worst).\n\nMorris Traversal: In-order with O(1) space using threaded binary tree.' },
    { q:'What is the difference between a stack and a queue?', a:'Stack (LIFO — Last In, First Out):\n- Operations: push (insert top), pop (remove top), peek (view top)\n- Use: function call stack, undo/redo, balanced parentheses, DFS, expression evaluation\n- Implement: array or linked list\n\nQueue (FIFO — First In, First Out):\n- Operations: enqueue (insert rear), dequeue (remove front), front (view front)\n- Use: BFS, job scheduling, printer queue, producer-consumer, cache eviction (LRU)\n- Implement: array (circular) or linked list\n\nDeque (Double-Ended Queue): Insert/delete at both ends. Implements both.\nPriority Queue: Dequeue based on priority. Implemented with Heap. O(log n) insert/extract.\nMonotonic Stack: Stack maintaining increasing/decreasing order. Used in next greater element problems.' },
    { q:'Graph algorithms — Dijkstra, Bellman-Ford, Floyd-Warshall.', a:'Dijkstra\'s Algorithm: Single-source shortest path in WEIGHTED graph (non-negative weights).\n- Uses min-heap (priority queue)\n- O((V + E) log V) time\n- Cannot handle negative weights\n\nBellman-Ford: Single-source shortest path. Handles NEGATIVE weights. Detects negative cycles.\n- O(V × E) time\n- Relax all edges V-1 times; if still relaxing on Vth iteration → negative cycle\n\nFloyd-Warshall: All-pairs shortest path. O(V³) time, O(V²) space.\n- DP approach: dp[i][j][k] = shortest path from i to j using first k vertices as intermediates\n\nMinimum Spanning Tree:\n- Kruskal\'s: Sort edges by weight, add if no cycle (Union-Find). O(E log E)\n- Prim\'s: Grow MST from a vertex using min-heap. O(E log V)' },
    { q:'What is a Trie? When do you use it?', a:'Trie (Prefix Tree): Tree data structure for string storage where each node represents a character.\n\nStructure: Root is empty. Each path from root to leaf represents a word. Nodes share common prefixes.\n\nOperations:\n- Insert: O(m) where m = word length\n- Search: O(m)\n- Prefix search (startsWith): O(m)\n\nSpace: O(ALPHABET_SIZE × m × n) — can be large.\n\nUse cases:\n- Autocomplete / search suggestions\n- Spell checker\n- IP routing tables\n- Word validation in games (Scrabble, Boggle)\n- Longest common prefix\n\nAlternatives: Radix/Patricia Trie (compressed), Aho-Corasick (multiple pattern matching).' },
  ],
  'System Design': [
    { q:'How would you design a URL shortener (bit.ly)?', a:'Requirements: Shorten URL, redirect, custom alias, expiry, analytics.\nScale: 100M URLs/day, 1B redirects/day.\n\nComponents:\n- API Server: POST /shorten → returns short URL\n- DB (Cassandra): shortCode → {originalURL, expiry, createdAt}\n- Cache (Redis): Hot short codes (80% cache hit expected)\n- Analytics Service: Kafka → ClickHouse for click counts\n\nShort code generation:\n- Base62 encoding of auto-incremented ID\n- Or: MD5(URL) → take first 6 chars (collision risk)\n- Or: Distributed counter (Zookeeper)\n\nRedirect flow: Request → Check Redis → If miss: DB → Return 302 → Async log click\n\nScaling: Load balancer → multiple API servers. Cassandra auto-shards. CDN for popular codes.' },
    { q:'How does a notification system work at scale?', a:'Requirements: Push (FCM/APNs), Email (SendGrid), SMS (Twilio). 10M/hour peak.\n\nArchitecture:\n1. Notification API: Accepts request, validates, checks user preferences\n2. Message Queue (Kafka): Topic per channel. Decouples producers from consumers.\n3. Channel Workers: Separate consumers for Push, Email, SMS\n4. Third-party providers: FCM/APNs, SendGrid/SES, Twilio\n5. Retry/DLQ: Failed messages retry 3x, then dead letter queue\n6. Status DB: Track delivery status per notification\n\nKey considerations:\n- Idempotency: Prevent duplicate delivery\n- Priority queues: Urgent notifications bypass queues\n- Rate limiting per user: Prevent spam\n- Template engine: Personalized messages at scale' },
    { q:'How would you design a rate limiter?', a:'Rate Limiter: Control how many requests a client can make in a time window.\n\nAlgorithms:\n1. Token Bucket: Tokens added at fixed rate; each request consumes one token. Allows bursts.\n2. Leaky Bucket: Queue with fixed drain rate. Smooth, predictable output.\n3. Fixed Window Counter: Count requests per window. Simple but boundary burst problem.\n4. Sliding Window Log: Exact but memory-intensive (store all timestamps).\n5. Sliding Window Counter: Fixed window + weighted previous window. Best balance.\n\nImplementation: Redis INCR + EXPIRE for distributed rate limiting.\nKey: "rate:user_id:minute_timestamp"\n\nResponse: HTTP 429 Too Many Requests + Retry-After header\n\nWhere to implement: API Gateway (best), nginx middleware, or application level.' },
    { q:'How would you design a chat system (like WhatsApp)?', a:'Core features: 1:1 messaging, group chat, online status, message delivery receipts.\n\nComponents:\n- WebSocket servers: Long-lived connections for real-time messaging\n- Message Queue (Kafka): Async message delivery, handles offline users\n- Message DB (Cassandra): Append-only, partitioned by conversation_id\n- Presence Service: Track online/offline status (Redis with TTL + heartbeat)\n- Push Notification: FCM/APNs for offline users\n- Media Storage: S3 + CDN for images/videos\n- Load Balancer: Sticky sessions for WebSocket connections\n\nMessage flow:\n1. Sender sends message via WebSocket\n2. Server saves to Cassandra, publishes to Kafka\n3. Consumer delivers to recipient WebSocket (if online) or push notification (if offline)\n4. Delivery receipts: single tick → double tick → blue tick' },
  ],
};

const SUBJECT_ICONS = {
  DBMS:'🗄️', OS:'💾', CN:'🌐', OOPs:'🧱', Java:'☕', Python:'🐍', DSA:'🌳', 'System Design':'🏗️'
};

const RESOURCE_LINKS = {
  DBMS:[{name:'GFG DBMS Questions',url:'https://www.geeksforgeeks.org/dbms-interview-questions/'},{name:'IndiaBix DBMS',url:'https://www.indiabix.com/database/questions-and-answers/'}],
  OS:[{name:'GFG OS Interview',url:'https://www.geeksforgeeks.org/operating-systems-interview-questions/'},{name:'Scaler OS Concepts',url:'https://www.scaler.com/topics/operating-system/'}],
  CN:[{name:'GFG CN Interview',url:'https://www.geeksforgeeks.org/computer-network-interview-questions/'},{name:'IndiaBix Networking',url:'https://www.indiabix.com/networking/questions-and-answers/'}],
  OOPs:[{name:'GFG OOPs Questions',url:'https://www.geeksforgeeks.org/oops-interview-questions/'},{name:'JavaTpoint OOPs',url:'https://www.javatpoint.com/oops-interview-questions'}],
  Java:[{name:'GFG Java Questions',url:'https://www.geeksforgeeks.org/java-interview-questions/'},{name:'JavaTpoint 500+ Java Q',url:'https://www.javatpoint.com/corejava-interview-questions'}],
  Python:[{name:'GFG Python Interview',url:'https://www.geeksforgeeks.org/python-interview-questions/'},{name:'InterviewBit Python',url:'https://www.interviewbit.com/python-interview-questions/'}],
  DSA:[{name:'GFG DSA Interview',url:'https://www.geeksforgeeks.org/data-structures-algorithms-interview-questions/'},{name:'LeetCode Problems',url:'https://leetcode.com/problemset/'}],
  'System Design':[{name:'System Design Primer',url:'https://github.com/donnemartin/system-design-primer'},{name:'ByteByteGo Blog',url:'https://blog.bytebytego.com/'}],
};

export default function TechnicalRoundPage() {
  const [activeSub, setActiveSub] = useState('DBMS');
  const [expanded, setExpanded]   = useState({});
  const [mode, setMode]           = useState('expandable');
  const [fcIdx, setFcIdx]         = useState(0);
  const [fcFlip, setFcFlip]       = useState(false);
  const [showRes, setShowRes]     = useState(false);

  const questions = TECH_QUESTIONS[activeSub] || [];
  const SUBJECTS  = Object.keys(TECH_QUESTIONS);
  const totalQ    = Object.values(TECH_QUESTIONS).flat().length;

  return (
    <div style={{fontFamily:"'Nunito',sans-serif"}}>
      <RoundHeader icon="🟠" title="Technical Round Practice"
        subtitle={`${SUBJECTS.length} subjects · ${totalQ} questions · Q&A + Flashcard mode`} />

      {/* Subject tabs */}
      <div style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:14}}>
        {SUBJECTS.map(s=>(
          <button key={s} onClick={()=>{setActiveSub(s);setExpanded({});setFcIdx(0);setFcFlip(false);setShowRes(false);}}
            style={{padding:'7px 14px',borderRadius:9,border:`1.5px solid ${activeSub===s?'#531697':'#d0d7e8'}`,background:activeSub===s?GRAD:'#fff',color:activeSub===s?'#fff':'#7a8ba8',fontWeight:800,cursor:'pointer',fontFamily:"'Nunito',sans-serif",fontSize:'.78rem',display:'flex',alignItems:'center',gap:5}}>
            <span>{SUBJECT_ICONS[s]||'📖'}</span>{s}
          </button>
        ))}
      </div>

      {/* Mode + Resources bar */}
      <div style={{display:'flex',gap:8,marginBottom:16,flexWrap:'wrap',alignItems:'center'}}>
        {[['expandable','📖 Q&A Mode'],['flashcard','🃏 Flashcard']].map(([m,lbl])=>(
          <button key={m} onClick={()=>{setMode(m);setFcIdx(0);setFcFlip(false);}}
            style={{padding:'7px 14px',borderRadius:8,border:`1px solid ${mode===m?'#13a1a5':'#d0d7e8'}`,background:mode===m?'rgba(19,161,165,0.08)':'#fff',color:mode===m?'#0d7a7e':'#7a8ba8',fontWeight:700,cursor:'pointer',fontFamily:"'Nunito',sans-serif",fontSize:'.78rem'}}>
            {lbl}
          </button>
        ))}
        <div style={{flex:1}}/>
        <span style={{fontSize:'.72rem',color:'#b0bec9',fontWeight:700}}>{questions.length} Q in {activeSub}</span>
        <button onClick={()=>setShowRes(r=>!r)}
          style={{padding:'7px 14px',borderRadius:8,border:`1px solid ${showRes?'#531697':'#d0d7e8'}`,background:showRes?'rgba(83,22,151,0.07)':'#fff',color:showRes?'#531697':'#7a8ba8',fontWeight:800,cursor:'pointer',fontFamily:"'Nunito',sans-serif",fontSize:'.78rem'}}>
          📚 {showRes?'Hide':'Resources'}
        </button>
      </div>

      {/* Resources Panel */}
      {showRes && (
        <Card style={{marginBottom:16,background:'rgba(83,22,151,0.03)',border:'1px solid rgba(83,22,151,0.12)'}}>
          <SectionTitle>📚 Resources for {activeSub}</SectionTitle>
          <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:10}}>
            {(RESOURCE_LINKS[activeSub]||[]).map((r,i)=>(
              <a key={i} href={r.url} target="_blank" rel="noreferrer"
                style={{padding:'7px 14px',borderRadius:8,background:'#fff',border:'1px solid #e8edf5',color:'#531697',fontWeight:700,textDecoration:'none',fontSize:'.78rem'}}>
                📖 {r.name} ↗
              </a>
            ))}
          </div>
          <div style={{fontSize:'.7rem',fontWeight:800,color:'#b0bec9',marginBottom:6}}>ALL TECHNICAL RESOURCES</div>
          <div style={{display:'flex',gap:6,flexWrap:'wrap'}}>
            {ROUND_RESOURCES.TECHNICAL.map((r,i)=>(
              <a key={i} href={r.url} target="_blank" rel="noreferrer"
                style={{padding:'4px 10px',borderRadius:6,background:r.color+'18',color:r.color,fontSize:'.7rem',fontWeight:800,textDecoration:'none',border:`1px solid ${r.color}30`}}>
                {r.tag} ↗
              </a>
            ))}
          </div>
        </Card>
      )}

      {/* Q&A Mode */}
      {mode==='expandable' && (
        <div style={{display:'flex',flexDirection:'column',gap:10}}>
          {questions.map((item,i)=>(
            <Card key={i} style={{padding:0,overflow:'hidden'}}>
              <button onClick={()=>setExpanded(e=>({...e,[i]:!e[i]}))}
                style={{width:'100%',display:'flex',alignItems:'center',gap:12,padding:'14px 18px',border:'none',background:'transparent',cursor:'pointer',textAlign:'left',fontFamily:"'Nunito',sans-serif"}}>
                <div style={{width:30,height:30,borderRadius:'50%',background:expanded[i]?GRAD:'#f0f3fa',color:expanded[i]?'#fff':'#531697',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'.78rem',fontWeight:800,flexShrink:0}}>Q{i+1}</div>
                <span style={{flex:1,fontWeight:700,fontSize:'.88rem',color:'#0f1a2e',textAlign:'left'}}>{item.q}</span>
                <span style={{color:'#531697',fontSize:'1rem',flexShrink:0,transform:expanded[i]?'rotate(180deg)':'none',transition:'transform .2s',display:'inline-block'}}>⌄</span>
              </button>
              {expanded[i]&&(
                <div style={{padding:'0 18px 16px'}}>
                  <div style={{padding:'14px 16px',borderRadius:10,background:'rgba(83,22,151,0.04)',border:'1px solid rgba(83,22,151,0.1)',fontSize:'.83rem',color:'#3d4e6b',lineHeight:1.85,whiteSpace:'pre-wrap'}}>{item.a}</div>
                </div>
              )}
            </Card>
          ))}
        </div>
      )}

      {/* Flashcard Mode */}
      {mode==='flashcard' && (
        <div style={{maxWidth:600,margin:'0 auto'}}>
          <Card style={{minHeight:300,display:'flex',flexDirection:'column',justifyContent:'center',cursor:'pointer',background:fcFlip?'rgba(83,22,151,0.04)':'#fff',border:`2px solid ${fcFlip?'rgba(83,22,151,0.2)':'#e8edf5'}`,transition:'all .3s'}}>
            <div onClick={()=>setFcFlip(f=>!f)} style={{flex:1,display:'flex',flexDirection:'column',justifyContent:'center',padding:'16px'}}>
              <div style={{fontSize:'.68rem',fontWeight:800,color:'#b0bec9',marginBottom:14,textAlign:'center'}}>{fcFlip?'💡 ANSWER':'❓ QUESTION'} — {activeSub} · {fcIdx+1}/{questions.length}</div>
              <div style={{fontSize:fcFlip?'.82rem':'.9rem',color:'#0f1a2e',fontWeight:fcFlip?400:700,lineHeight:1.8,textAlign:'center',whiteSpace:'pre-wrap'}}>
                {fcFlip?questions[fcIdx]?.a:questions[fcIdx]?.q}
              </div>
              {!fcFlip&&<div style={{textAlign:'center',marginTop:18,fontSize:'.72rem',color:'#b0bec9'}}>Click to reveal answer</div>}
            </div>
          </Card>
          <div style={{display:'flex',justifyContent:'center',gap:10,marginTop:14}}>
            <button onClick={()=>{setFcIdx(i=>Math.max(0,i-1));setFcFlip(false);}} disabled={fcIdx===0}
              style={{padding:'9px 20px',borderRadius:9,border:'1px solid #d0d7e8',background:fcIdx===0?'#f8f9fc':'#fff',color:fcIdx===0?'#b0bec9':'#531697',fontWeight:800,cursor:fcIdx===0?'default':'pointer',fontFamily:"'Nunito',sans-serif"}}>← Prev</button>
            <button onClick={()=>setFcFlip(f=>!f)}
              style={{padding:'9px 20px',borderRadius:9,border:'none',background:GRAD,color:'#fff',fontWeight:800,cursor:'pointer',fontFamily:"'Nunito',sans-serif"}}>{fcFlip?'Show Q':'Show A'}</button>
            <button onClick={()=>{setFcIdx(i=>Math.min(questions.length-1,i+1));setFcFlip(false);}} disabled={fcIdx===questions.length-1}
              style={{padding:'9px 20px',borderRadius:9,border:'1px solid #d0d7e8',background:fcIdx===questions.length-1?'#f8f9fc':'#fff',color:fcIdx===questions.length-1?'#b0bec9':'#531697',fontWeight:800,cursor:fcIdx===questions.length-1?'default':'pointer',fontFamily:"'Nunito',sans-serif"}}>Next →</button>
          </div>
          <div style={{display:'flex',gap:4,justifyContent:'center',marginTop:10,flexWrap:'wrap'}}>
            {questions.map((_,i)=><div key={i} onClick={()=>{setFcIdx(i);setFcFlip(false);}} style={{width:8,height:8,borderRadius:'50%',background:i===fcIdx?'#531697':'#e8edf5',cursor:'pointer'}}/>)}
          </div>
        </div>
      )}
    </div>
  );
}
