require('dotenv').config();
const mongoose = require('mongoose');

async function seed() {
  const uri = process.env.MONGODB_URI;
  await mongoose.connect(uri);
  console.log('✅ Connected to MongoDB\n');

  const { Company, Problem, AptitudeQuestion } = require('../models/index');

  // ─── RESET COMPANY + APTITUDE + PROBLEMS (NOT USERS) ──────────────────────
  await Company.deleteMany({});
  await AptitudeQuestion.deleteMany({});
  await Problem.deleteMany({});
  console.log('🧹 Old Companies, Aptitude & Problems removed\n');

  // ═══════════════════════════════════════════════════════════════════════════
  // 🏢 COMPANIES — Fully detailed with comparison-ready data
  // ═══════════════════════════════════════════════════════════════════════════
  const companies = [
    {
      name: "TCS",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Tata_Consultancy_Services_old_logo.svg/1280px-Tata_Consultancy_Services_old_logo.svg.png",
      sector: "IT Services",
      website: "https://tcs.com",
      status: "visited",
      campusVisitDate: new Date("2024-09-15"),
      ctc: "3.36–7 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE","Mechanical","Civil"], backlogs: false },
      roles: ["System Engineer","Digital Specialist Engineer","Ninja (Smart Hiring)"],
      recruitmentRounds: ["NQT Aptitude Test (Verbal + Quant + Reasoning)","Advanced Coding Round (Digital roles)","Technical Interview (Core CS)","Managerial + HR Interview"],
      aptitudePatterns: "Quant: Percentages, Time & Work, Profit & Loss, Speed-Distance\nLogical: Coding-Decoding, Blood Relations, Syllogism\nVerbal: RC, Sentence Correction, Fill in Blanks\nAdvanced Coding: 2 problems, 30 min for Digital/Ninja track",
      interviewPatterns: "OOP (4 pillars with examples)\nDBMS normalization, joins, indexing\nOS: deadlock, paging, scheduling\nCN basics: TCP/IP, OSI model\n1 coding problem from arrays/strings\nProject explanation in depth",
      jdText: "TCS hires freshers for large-scale enterprise IT systems. Required skills: Java, Python, SQL, REST APIs, Data Structures, Algorithms, MySQL, C++. Work includes development, testing, maintenance across banking, retail, healthcare verticals. Candidates undergo 3-month ILP training. Bond: 1 year.",      prepTips: "Practice RS Aggarwal for aptitude speed.\nSolve 50+ LeetCode Easy problems.\nPrepare 2-min project explanation.\nRevise OOP, DBMS, and OS thoroughly.",
      tags: ["mass-recruiter","bond","service-based","training-provided"],
      companyOverview: "India's largest IT company (Tata Group). Revenue: $27B+. Employees: 600,000+. Operates in 46 countries. Bulk campus recruitment through NQT. Strong training (ILP - Initial Learning Program) for freshers.",
      techStack: ["Java","Python","SQL","Spring Boot","REST APIs","Cloud Basics"],
      workCulture: "Structured hierarchy. Large team environment. Work from office/hybrid. Strong training program. Rotational project assignments based on performance.",
      growthPath: "System Engineer → Senior → IT Analyst → Consultant → Manager (avg 3–4 years per level)",
      interviewDifficulty: "Easy-Medium",
      bondDetails: "1 year service bond. Penalty: ~₹50,000 if broken.",
      hiringMode: "Mass Campus",
      testPlatform: "TCS iON",
      bond: "1 year",
      packageBreakdown: "Base: ₹3.36 LPA (SE), Digital: ₹7 LPA, Ninja: ₹7 LPA",
    },
    {
      name: "Infosys",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg",
      sector: "IT Services",
      website: "https://infosys.com",
      status: "visited",
      campusVisitDate: new Date("2024-10-05"),
      ctc: "3.6–9.5 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 6.5, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Systems Engineer","Specialist Programmer","Power Programmer"],
      recruitmentRounds: ["InfyTQ / HackWithInfy Assessment","Pseudocode + Aptitude OA","Coding Round (SP/PP)","Technical Interview","HR Round"],
      aptitudePatterns: "Pseudocode Tracing: 15+ questions (most important!)\nQuant: Time & Work, Ratios, Percentages\nLogical puzzles and verbal reasoning\nSP/PP: HackerRank — 2–3 coding problems, Medium difficulty",
      interviewPatterns: "Linked list reversal, cycle detection\nTree traversal (in-order, pre-order, post-order)\nDBMS joins, normalization (1NF–BCNF)\nOOP concepts with real-world examples\nProject tech stack walkthrough",
      jdText: "Infosys hires for SE and SP tracks. Required skills: Java, Python, SQL, Data Structures, Algorithms, REST APIs, MySQL, JavaScript. SP track: competitive coding, System Design, C++. Work domains: banking, insurance, retail, enterprise. Bond: 1 year.",      prepTips: "Practice pseudocode tracing on InfyTQ platform.\nSolve LeetCode medium problems (arrays, strings, trees).\nRevise OOP and DBMS thoroughly.\nFor SP: HackerRank medium/hard practice.",
      tags: ["multi-track","pseudocode","SP-coding","training-provided"],
      companyOverview: "Global IT leader. Revenue: $18B+. Employees: 350,000+. Operates in 56 countries. Multiple hiring tracks with different salary bands. Known for InfyTQ campus platform.",
      techStack: ["Java","Python","SQL","Spring Boot","Cloud","Microservices"],
      workCulture: "Collaborative. Strong L&D (Infosys Learning Platform). Large campuses in Mysuru, Bengaluru, Pune. Work from office primarily.",
      growthPath: "Systems Engineer → Senior SE → Tech Lead → Consultant → Senior Consultant",
      interviewDifficulty: "Easy (SE) / Medium-Hard (SP/PP)",
      bondDetails: "1 year bond for SE track. No bond for SP/PP.",
      hiringMode: "Campus + InfyTQ",
      testPlatform: "InfyTQ / HackerRank",
      bond: "1 year (SE track)",
      packageBreakdown: "SE: ₹3.6 LPA, SP: ₹6.5–9.5 LPA, PP: ₹9.5+ LPA",
    },
    {
      name: "Wipro",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Wipro_Primary_Logo_Color_RGB.svg",
      sector: "IT Services",
      website: "https://wipro.com",
      status: "visited",
      campusVisitDate: new Date("2024-10-20"),
      ctc: "3.5–6.5 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE","Mechanical","Civil"], backlogs: false },
      roles: ["Project Engineer","Elite NLTH Engineer","Turbo Graduate Engineer"],
      recruitmentRounds: ["NLTH Online Test (Aptitude + Communication)","Essay Writing (500 words)","Technical Interview","HR Interview"],
      aptitudePatterns: "Aptitude: 50Q/50min — Quant, Reasoning, Verbal\nEssay Writing: Current affairs topic, 500 words, 20 min\nElite/Turbo: 2 coding problems in Python or Java",
      interviewPatterns: "String/Array coding problems\nTCP vs UDP, OSI model\nACID properties in DBMS\nOOP concepts (abstract class vs interface)\nProject explanation",
      jdText: "Wipro NLTH requires Python, Java, SQL, Data Structures, Algorithms, C++, MySQL, REST APIs. Turbo track demands competitive DSA skills. Essay writing differentiates candidates. Service-based roles in manufacturing, BFSI, telecom. Bond: 18 months.",      prepTips: "Essay writing practice on current tech topics is crucial.\nSolve 60+ LeetCode Easy-Medium.\nFocus on communication skills.\nPractice Wipro NLTH previous papers.",
      tags: ["mass-recruiter","essay-writing","communication","accessible"],
      companyOverview: "Wipro Limited. Revenue: $11B+. Employees: 240,000+. Operates in 65 countries. Diverse hiring tracks. Works in cloud, cybersecurity, data analytics.",
      techStack: ["Java","Python","SQL","HTML/CSS","JavaScript","REST APIs"],
      workCulture: "Large teams. Good work-life balance. Multiple transfer options. Strong L&D programs. Hybrid work policies.",
      growthPath: "Project Engineer → Senior PE → Tech Lead → Solution Architect",
      interviewDifficulty: "Easy",
      bondDetails: "18 months service bond. Penalty: ~₹75,000 if broken.",
      hiringMode: "Mass Campus (NLTH)",
      testPlatform: "AMCAT / Cocubes",
      bond: "18 months",
      packageBreakdown: "Project Engineer: ₹3.5 LPA, Elite: ₹4.5 LPA, Turbo: ₹6.5 LPA",
    },
    {
      name: "Cognizant",
      logoUrl: "https://cdn.worldvectorlogo.com/logos/cognizant-3.svg",
      sector: "IT Services",
      website: "https://cognizant.com",
      status: "visited",
      campusVisitDate: new Date("2024-11-02"),
      ctc: "4–7 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Programmer Analyst Trainee","GenC","GenC Next","GenC Elevate"],
      recruitmentRounds: ["GenC Online Test (Cocubes — Aptitude + Pseudocode + SDLC MCQ)","Coding Round (GenC Next/Elevate)","Technical + HR Combined Interview"],
      aptitudePatterns: "Pseudocode Tracing: 20Q (critical differentiator)\nQuant: 20Q — Profit & Loss, Permutations, Time & Work\nLogical: 20Q — seating, directions\nAutomation Concepts: 10Q on SDLC, testing basics",
      interviewPatterns: "Write program for string reversal or palindrome\nExplain normalization (1NF–3NF with examples)\nAgile/Scrum methodology\nDBMS: GROUP BY, HAVING, subqueries\nProject tech stack and challenges",
      jdText: "Cognizant GenC requires Java, Python, SQL, Data Structures, Algorithms, MySQL, C++, REST APIs. GenC Next: strong coding, JavaScript, React. GenC Elevate: advanced DSA, System Design. BFSI, healthcare, retail focus. Bond: 1.5 years.",      prepTips: "Pseudocode tracing is the #1 differentiator — practice heavily.\nLearn Agile/Scrum terminology.\nFocus on SDLC life cycle questions.\nRevise all OOP concepts with examples.",
      tags: ["mass-recruiter","pseudocode","agile","tiered-hiring"],
      companyOverview: "Cognizant Technology Solutions. Revenue: $19B+. Employees: 350,000+. Operates in 40+ countries. Strong digital transformation practice. BFSI, healthcare, retail focus.",
      techStack: ["Java","Python","SQL","React","Selenium","Cloud Fundamentals"],
      workCulture: "Process-driven. Client-focused teams. Good L&D (Cognizant Academy). US client exposure. Hybrid work model.",
      growthPath: "PAT → Programmer Analyst → Senior PA → Associate Manager → Manager",
      interviewDifficulty: "Easy",
      bondDetails: "1.5 year service bond.",
      hiringMode: "Mass Campus (Cocubes/AMCAT)",
      testPlatform: "Cocubes / AMCAT",
      bond: "1.5 years",
      packageBreakdown: "GenC: ₹4 LPA, GenC Next: ₹5.5 LPA, GenC Elevate: ₹7 LPA",
    },
    {
      name: "Capgemini",
      logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqz2rnBhUydI2Yd47HawYx8kOaboS3DPROGA&s",
      sector: "IT Consulting",
      website: "https://capgemini.com",
      status: "visited",
      campusVisitDate: new Date("2024-11-15"),
      ctc: "3.8–7 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE","Mechanical"], backlogs: false },
      roles: ["Analyst","Senior Analyst","Associate Consultant"],
      recruitmentRounds: ["Aptitude Test (AMCAT/Cocubes — Pseudocode + Quant)","Essay Writing","Technical Interview","HR Interview"],
      aptitudePatterns: "Pseudocode Tracing: Very common\nQuant: Percentages, Ratios, Mensuration\nVerbal: Sentence ordering, vocabulary\nEssay: Short tech/social topic",
      interviewPatterns: "Java Fibonacci implementation\nPolymorphism real-world example\nDBMS: DELETE vs TRUNCATE vs DROP\nAgile methodology basics\nProject architecture explanation",
      jdText: "Capgemini requires Python, Java, SQL, JavaScript, HTML, CSS, REST APIs, MySQL, Data Structures, Algorithms, Git. Application development, cloud migration, testing roles. Essay writing is important filter. Bond: 1 year.",      prepTips: "Practice essay writing on GD topics.\nRevise pseudocode tracing from previous papers.\nBrush up on Agile methodology.\nNo coding round for standard track — focus on aptitude.",
      tags: ["mass-recruiter","essay","inclusive","no-coding-round"],
      companyOverview: "French multinational. Revenue: $22B+. Employees: 350,000+. One of world's largest IT companies. Cloud services, digital engineering, enterprise IT.",
      techStack: ["Java","Python","SQL","Selenium","Azure/AWS","Agile"],
      workCulture: "Inclusive, diverse culture. Good work-life balance. Strong L&D. Client rotation across domains.",
      growthPath: "Analyst → Senior Analyst → Consultant → Senior Consultant → Manager",
      interviewDifficulty: "Easy",
      bondDetails: "1 year service bond.",
      hiringMode: "Mass Campus",
      testPlatform: "AMCAT / Cocubes",
      bond: "1 year",
      packageBreakdown: "Analyst: ₹3.8 LPA, Senior Analyst: ₹5.5 LPA",
    },
    {
      name: "Accenture",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Accenture.svg",
      sector: "IT Consulting",
      website: "https://accenture.com",
      status: "upcoming",
      ctc: "4.5–8 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 6.5, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Associate Software Engineer","AI Solutions Associate","Packaged App Developer"],
      recruitmentRounds: ["Cognitive & Technical Assessment (90 min)","AI Video Communication Test","Technical Interview","HR Interview"],
      aptitudePatterns: "Cognitive: Logical, Verbal, Mathematical — 60Q total\nTechnical MCQs: OOP, DS, Algorithm basics — 20Q\nCommunication: 2 AI-scored video questions",
      interviewPatterns: "Find bugs in given code snippets\nDBMS normalization (1NF–BCNF)\nML model lifecycle (for AIS role)\nCode debugging exercises\nProject explanation and challenges",
      jdText: "Accenture ASE requires Java, Python, SQL, JavaScript, Data Structures, Algorithms, REST APIs, Git. AIS track requires Machine Learning, Python, TensorFlow, Data Analysis, Deep Learning, NumPy, Pandas. Cloud: AWS, Docker. No bond.",      prepTips: "Communication Assessment is make-or-break — record and practice speaking.\nRevise OOP and DBMS thoroughly.\nPrepare ML basics for AIS track.\nPractice code debugging exercises.",
      tags: ["AIS-track","communication-test","AI","no-bond"],
      companyOverview: "Global consulting & tech leader. Revenue: $64B+. Employees: 750,000+. Operations in 120 countries. AIS track highly valuable for AIML students.",
      techStack: ["Java","Python","React","SQL","Azure","Machine Learning Basics"],
      workCulture: "Dynamic, client-facing. High learning curve. Strong AI & Cloud training. Global project rotation possible. Hybrid/remote flexible.",
      growthPath: "ASE → SE → Senior SE → Manager → Senior Manager",
      interviewDifficulty: "Medium",
      bondDetails: "No service bond.",
      hiringMode: "Campus + Online",
      testPlatform: "Accenture Internal Platform",
      bond: "None",
      packageBreakdown: "ASE: ₹4.5 LPA, AIS (AIML): ₹8 LPA",
    },
    {
      name: "Persistent Systems",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Persistent_Systems_Logo.svg/3840px-Persistent_Systems_Logo.svg.png",
      sector: "Product Engineering",
      website: "https://persistent.com",
      status: "upcoming",
      ctc: "4–8 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 7.0, allowedBranches: ["CSE","CSAIML","IT"], backlogs: false },
      roles: ["Software Engineer","Product Developer","Trainee Engineer"],
      recruitmentRounds: ["AMCAT Aptitude (Proctored Online)","HackerRank Coding Round (2 problems, 60 min)","Technical Interview (1–2 rounds)","HR Interview"],
      aptitudePatterns: "AMCAT: Logical 25Q, Quant 25Q, English 25Q, Coding 2Q\nCoding: Arrays, strings, number theory, basic recursion\nMedium difficulty DSA problems",
      interviewPatterns: "Deep project dive (explain every function)\nOOP with design examples (SOLID principles)\nDBMS: ER diagram to schema, JOIN types\nAlgorithm complexities (all sorting)\nGitHub portfolio review",
      jdText: "Persistent Systems requires React, Node.js, JavaScript, TypeScript, Python, Java, SQL, MongoDB, REST APIs, Docker, AWS, Git, Data Structures, Algorithms, Microservices, System Design. Full-stack development. CGPA 7.0+ required. No bond.",      prepTips: "Have 2 strong GitHub projects with documentation.\nSolve 100+ LeetCode problems.\nStudy Persistent previous interview questions on GFG.\nPrepare SOLID principles and design patterns.",
      tags: ["product-based","github","high-cgpa","no-bond"],
      companyOverview: "Pune-based product engineering company. Revenue: $1B+. Employees: 23,000+. Works in healthcare, BFSI, high-tech. Strong engineering culture.",
      techStack: ["Java","Python","Node.js","React","Docker","Kubernetes","AWS"],
      workCulture: "Engineering-focused. Good work-life balance. Strong mentorship. Tech conferences and hackathons. Hybrid work.",
      growthPath: "Trainee Engineer → SE → Senior SE → Tech Lead → Architect",
      interviewDifficulty: "Medium",
      bondDetails: "No service bond.",
      hiringMode: "Campus AMCAT + HackerRank",
      testPlatform: "AMCAT + HackerRank",
      bond: "None",
      packageBreakdown: "Trainee: ₹4 LPA, SE: ₹6–8 LPA",
    },
    {
      name: "Tech Mahindra",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Tech_Mahindra_New_Logo.svg/1280px-Tech_Mahindra_New_Logo.svg.png",
      sector: "IT Services & Telecom",
      website: "https://techmahindra.com",
      status: "upcoming",
      ctc: "3.25–6 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE","Mechanical"], backlogs: false },
      roles: ["Software Engineer","Associate Software Engineer","AI/ML Track"],
      recruitmentRounds: ["AMCAT / Internal Online Test","Coding Round (1–2 problems)","Technical Interview","HR Interview"],
      aptitudePatterns: "Logical: 20Q, Quant: 20Q, English: 20Q, Technical MCQ: 20Q\nAI/ML track: additional ML theory questions\nCoding: Easy-Medium DSA problems",
      interviewPatterns: "OSI model explanation\nInheritance with real example\nString palindrome code\nML algorithms for AI track (Random Forest, SVM, CNN)\nProject discussion",
      jdText: "Tech Mahindra requires Python, Java, SQL, Data Structures, Algorithms, C++, MySQL, REST APIs. AI/ML track: Machine Learning, Deep Learning, TensorFlow, Pandas, NumPy. 5G telecom focus. Standard SE: JavaScript, HTML, CSS. No bond.",      prepTips: "For AI track: prepare ML algorithms, confusion matrix, ROC curve.\nStudy networking basics — OSI, TCP/IP.\nRevise OOP and basic DSA.\nPractice coding in Java or Python.",
      tags: ["AI-track","telecom","mass-recruiter","no-bond"],
      companyOverview: "Mahindra Group IT arm. Revenue: $6B+. Employees: 160,000+. Telecom, IT, BPO services. 5G and digital transformation focus.",
      techStack: ["Java","Python","SQL","Networking","5G Concepts","Cloud"],
      workCulture: "Good work culture. Telecom domain exposure. Internal training on emerging tech. Hybrid model.",
      growthPath: "ASE → SE → Tech Lead → Solution Architect",
      interviewDifficulty: "Easy",
      bondDetails: "No bond typically.",
      hiringMode: "Mass Campus + Online",
      testPlatform: "AMCAT / Internal",
      bond: "None",
      packageBreakdown: "ASE: ₹3.25 LPA, AI Track: ₹5–6 LPA",
    },
    {
      name: "Hexaware Technologies",
      logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMFIZ-c9plDnV3Ir2Dvp09vbDh0vSl_foPDg&s",
      sector: "IT Services & BPO",
      website: "https://hexaware.com",
      status: "upcoming",
      ctc: "3.5–6 LPA",
      difficulty: "Easy",
      eligibilityCriteria: { minCGPA: 6.0, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Graduate Engineer Trainee","Software Engineer"],
      recruitmentRounds: ["Online Aptitude Test (Verbal + Quant + Logical + Basic Coding)","Technical Interview","HR Round"],
      aptitudePatterns: "Quant: Percentages, Averages, Number Series\nLogical: Pattern recognition, syllogism\nVerbal: Grammar, RC\nCoding: 1–2 Easy problems",
      interviewPatterns: "OOP vs Procedural programming\nSQL: second highest salary query\nProject description and technologies used\nBasic Java/Python programs",
      jdText: "Hexaware Technologies requires Python, Java, SQL, MySQL, Data Structures, Algorithms, REST APIs, JavaScript, Git, Selenium. Automation focus. AI tools: Machine Learning, Data Analysis. BFSI, healthcare, manufacturing. Fast growth culture.",      prepTips: "Practice SQL queries — joins, subqueries, aggregates.\nRevise OOP with Java examples.\nPrepare HR questions around adaptability and teamwork.",
      tags: ["automation","BFSI","supportive-culture","accessible"],
      companyOverview: "Global IT and BPO company. Employees: 32,000+. Mumbai HQ. Automation-led transformation focus. Works in BFSI, healthcare, travel.",
      techStack: ["Java","Python","SQL","Selenium","REST APIs","Cloud Basics"],
      workCulture: "Supportive work environment. Good learning culture. Fast growth for performers. Hybrid work.",
      growthPath: "GET → SE → Senior SE → Lead",
      interviewDifficulty: "Easy",
      bondDetails: "No bond.",
      hiringMode: "Campus",
      testPlatform: "Internal / AMCAT",
      bond: "None",
      packageBreakdown: "GET: ₹3.5 LPA, SE: ₹5–6 LPA",
    },
    {
      name: "Amdocs",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Amdocs-2017-brand-mark.svg/1280px-Amdocs-2017-brand-mark.svg.png",
      sector: "Telecom IT Solutions",
      website: "https://amdocs.com",
      status: "upcoming",
      ctc: "4–8 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 6.5, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Software Developer","Associate Software Engineer","QA Engineer"],
      recruitmentRounds: ["Online Aptitude + Coding Test","Technical Interview Round 1 (DSA + OOP)","Technical Interview Round 2 (System Design + APIs)","HR Round"],
      aptitudePatterns: "Quant: Number theory, Percentages, Ratios\nLogical: Puzzles, seating arrangements\nCoding: 1–2 Easy-Medium DSA problems",
      interviewPatterns: "Implement stack using queues\nREST vs SOAP API comparison\nSQL for finding duplicate records\nSystem design basics (APIs, databases)\nTelecom domain awareness (BSS/OSS)",
      jdText: "Amdocs requires Java, Python, SQL, MySQL, Data Structures, Algorithms, REST APIs, Microservices, System Design, JavaScript, Git, Docker. Works with telecom: AT&T, T-Mobile. Strong technical bar for dev roles.",      prepTips: "Learn basics of telecom — BSS, OSS, billing systems.\nSolve Medium LeetCode problems consistently.\nPrepare REST API concepts thoroughly.\nStudy microservices architecture.",
      tags: ["telecom-domain","enterprise-products","global-clients"],
      companyOverview: "Global telecom software provider. Revenue: $4.5B+. Employees: 30,000+. Missouri HQ. Serves 350+ telecom operators globally.",
      techStack: ["Java","Python","SQL","Linux","REST APIs","Microservices","Telecom Protocols"],
      workCulture: "Technical culture. Good exposure to enterprise-scale systems. Telecom domain expertise. US client interaction.",
      growthPath: "Associate SE → SE → Senior SE → Lead → Architect",
      interviewDifficulty: "Medium",
      bondDetails: "No bond.",
      hiringMode: "Campus + Online",
      testPlatform: "HackerRank / Internal",
      bond: "None",
      packageBreakdown: "Associate SE: ₹4 LPA, SE: ₹6–8 LPA",
    },
    {
      name: "PayPal",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg",
      sector: "Fintech",
      website: "https://paypal.com",
      status: "expected",
      ctc: "12–20 LPA",
      difficulty: "Hard",
      eligibilityCriteria: { minCGPA: 7.5, allowedBranches: ["CSE","CSAIML","IT"], backlogs: false },
      roles: ["Software Engineer (University Hire)","Data Engineer","SRE Associate"],
      recruitmentRounds: ["Online Coding Test (2–3 DSA problems, Hard level)","Technical Interview Round 1 (DSA + Complexity)","Technical Interview Round 2 (System Design)","HR / Culture Fit Round"],
      aptitudePatterns: "No traditional aptitude — purely DSA focused\nGraphs, Trees, DP, Greedy algorithms\nTime and space complexity analysis required",
      interviewPatterns: "Implement LRU Cache\nShortest path in weighted graph\nDesign payment gateway system\nBehavioral questions aligned with PayPal values\nLow-level design problems",
      jdText: "Global fintech leader. Payment systems, fraud detection, API development. India offices in Chennai, Bengaluru. Excellent compensation and mentorship. High technical bar — Medium/Hard LeetCode level required.",      prepTips: "Solve 200+ LeetCode problems, focus on Medium/Hard.\nStudy system design: caching, load balancing, databases.\nPractice behavioral interviews using STAR method.\nUnderstand payment systems architecture.",
      tags: ["fintech","high-package","hard-interview","system-design"],
      companyOverview: "Global digital payments leader. Revenue: $29B+. Employees: 28,000+. Serves 400M+ active accounts. Strong India engineering team in Chennai and Bengaluru.",
      techStack: ["Java","Python","Node.js","React","Kafka","Kubernetes","AWS"],
      workCulture: "Engineering excellence culture. Fast-paced fintech environment. Strong mentorship programs. Excellent work-life balance for a top tech company.",
      growthPath: "SWE → SWE II → Senior SWE → Staff SWE → Principal",
      interviewDifficulty: "Hard",
      bondDetails: "No bond.",
      hiringMode: "Direct Campus + Online",
      testPlatform: "HackerRank",
      bond: "None",
      packageBreakdown: "SWE: ₹12–20 LPA (base + stock)",
    },
    {
      name: "Google",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
      sector: "Technology (Search, Cloud, AI)",
      website: "https://careers.google.com",
      status: "expected",
      ctc: "20–45 LPA",
      difficulty: "Hard",
      eligibilityCriteria: { minCGPA: 8.0, allowedBranches: ["CSE","CSAIML","IT"], backlogs: false },
      roles: ["Software Engineer (University Graduate)","Site Reliability Engineer","Research Engineer"],
      recruitmentRounds: ["Resume Shortlisting (GPA + CP history)","Online Coding Test (2–3 Hard DSA)","Phone/Video Interview x2","Onsite Virtual (3–5 rounds — DSA + System Design + Googleyness)"],
      aptitudePatterns: "No aptitude — purely algorithmic\nGraphs, DP, segment trees, advanced data structures\nHard LeetCode level problems",
      interviewPatterns: "Design Google Maps routing algorithm\nImplement thread-safe LRU cache\nOptimize O(n²) to O(n log n)\nSystem design: distributed storage, load balancers\nGoogleyness behavioral round",
      jdText: "Google requires Data Structures, Algorithms, System Design, Python, Java, C++, Machine Learning, Deep Learning, Golang, Kubernetes, Docker, AWS, GCP, SQL, Distributed Systems, REST APIs. Highly competitive campus process.",      prepTips: "Solve 300+ LeetCode including Hard.\nStudy system design from 'Designing Data-Intensive Applications'.\nPractice with mock interviews on Pramp/interviewing.io.\nRead 'Cracking the Coding Interview'.",
      tags: ["FAANG","highest-package","hardest-interview","research"],
      companyOverview: "World's most valuable tech company. Revenue: $307B+. Products: Search, Maps, YouTube, Android, Cloud, AI. India offices are major engineering hubs.",
      techStack: ["C++","Java","Python","Go","Kubernetes","BigQuery","TensorFlow"],
      workCulture: "Innovative, autonomous culture. 20% project time. World-class perks. Strong technical mentorship. Open discussion culture.",
      growthPath: "L3 (SWE) → L4 → L5 (Senior) → L6 (Staff) → L7 (Principal)",
      interviewDifficulty: "Very Hard",
      bondDetails: "No bond.",
      hiringMode: "Direct Resume + Referral",
      testPlatform: "Google Docs / CoderPad",
      bond: "None",
      packageBreakdown: "L3: ₹20–30 LPA base + ESOPs worth ₹15–30 LPA",
    },
    {
      name: "Microsoft",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
      sector: "Technology (Cloud, Software, AI)",
      website: "https://careers.microsoft.com",
      status: "expected",
      ctc: "20–45 LPA",
      difficulty: "Hard",
      eligibilityCriteria: { minCGPA: 7.5, allowedBranches: ["CSE","CSAIML","IT"], backlogs: false },
      roles: ["Software Engineer","Program Manager","Data & Applied Scientist"],
      recruitmentRounds: ["Resume Shortlisting","Online Coding Test (2–3 Medium-Hard)","Technical Interview x3","HR / As Appropriate (AA) Round"],
      aptitudePatterns: "No aptitude — DSA + system design\nTrees, graphs, DP, string algorithms, design patterns\nGrowth mindset behavioral evaluation",
      interviewPatterns: "Serialize and deserialize binary tree\nDesign URL shortener\nTask scheduler with priority queues\nSystem design: Azure patterns\nGrowth mindset behavioral questions",
      jdText: "Microsoft requires Data Structures, Algorithms, System Design, Python, Java, C++, TypeScript, JavaScript, React, Azure, Docker, Kubernetes, SQL, PostgreSQL, REST APIs, Microservices, Git. Products: Azure, GitHub, Office 365.",      prepTips: "Solve 200–300 LeetCode including graphs and DP.\nStudy system design — Azure architecture is bonus.\nPractice Growth Mindset behavioral questions (STAR).\nExplore GitHub and Azure documentation.",
      tags: ["FAANG","azure","growth-mindset","high-package"],
      companyOverview: "Global tech leader. Revenue: $200B+. Products: Windows, Azure, GitHub, LinkedIn, Xbox. Major India presence in Hyderabad (5000+ engineers).",
      techStack: ["C#","C++","Python","Azure","TypeScript","React","Kubernetes","ML"],
      workCulture: "Collaborative, inclusive. Growth mindset culture. Strong mentorship. Hybrid work. Excellent benefits and ESOPs.",
      growthPath: "SDE (59/60) → SDE II (63/64) → Senior SDE (65/66) → Principal",
      interviewDifficulty: "Hard",
      bondDetails: "No bond.",
      hiringMode: "Direct Campus + Referral",
      testPlatform: "CoderPad / HackerRank",
      bond: "None",
      packageBreakdown: "SWE: ₹20–30 LPA base + ESOPs",
    },
    {
      name: "KPIT Technologies",
      logoUrl: "https://lapentor-sphere.s3.amazonaws.com/uploads/vr/5d78bea2ffd0e1091ea5bcda/asset/1568613259-0.jpg",
      sector: "Automotive IT & Engineering",
      website: "https://kpit.com",
      status: "expected",
      ctc: "4–8 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 6.5, allowedBranches: ["CSE","CSAIML","IT","ECE"], backlogs: false },
      roles: ["Embedded Software Engineer","AUTOSAR Developer","Python Developer"],
      recruitmentRounds: ["Online Test (Aptitude + C/C++ MCQs)","Technical Interview Round 1 (C/C++ + OS + Embedded)","Technical Interview Round 2 (Automotive Protocols)","HR Round"],
      aptitudePatterns: "Quant: Basic aptitude\nTechnical: C pointers, bit manipulation, OS, embedded MCQs\nFocus on memory management and RTOS",
      interviewPatterns: "Memory segmentation in C explanation\nSemaphore in RTOS\nCAN vs LIN protocol differences\nPointer arithmetic programs\nAUTOSAR architecture overview",
      jdText: "KPIT Technologies requires C++, Python, Java, Embedded Systems, SQL, Data Structures, Algorithms, AUTOSAR, REST APIs, Git, Linux, Machine Learning. Automotive software: BMW, Volkswagen, Toyota. EV powertrain software focus.",      prepTips: "Deep dive into C/C++ pointers and memory management.\nStudy AUTOSAR layered architecture.\nLearn CAN protocol basics from documentation.\nPractice low-level programming concepts.",
      tags: ["automotive","embedded","AUTOSAR","niche-domain"],
      companyOverview: "Pune-based automotive software company. Revenue: $700M+. Works with top OEMs globally. Specialized in EV, ADAS, and connected vehicles software.",
      techStack: ["C","C++","Python","AUTOSAR","CAN Protocol","RTOS","Linux"],
      workCulture: "Engineering-focused. Domain expertise development. Good work culture. Pune-based work. Exposure to automotive industry.",
      growthPath: "Junior SE → SE → Senior SE → Tech Lead → Domain Expert",
      interviewDifficulty: "Medium",
      bondDetails: "No bond.",
      hiringMode: "Campus + Online",
      testPlatform: "Internal Platform",
      bond: "None",
      packageBreakdown: "Junior SE: ₹4 LPA, SE: ₹6–8 LPA",
    },
    {
      name: "BNY Mellon",
      logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/BNY_Mellon.svg/1280px-BNY_Mellon.svg.png",
      sector: "Financial Technology",
      website: "https://bnymellon.com",
      status: "expected",
      ctc: "8–18 LPA",
      difficulty: "Medium",
      eligibilityCriteria: { minCGPA: 7.0, allowedBranches: ["CSE","CSAIML","IT"], backlogs: false },
      roles: ["Technology Analyst","Software Engineer","Data Engineer"],
      recruitmentRounds: ["Online Coding Test (2–3 DSA + Aptitude)","Technical Interview Round 1 (DSA + Java OOP)","Technical Interview Round 2 (System Design + Finance Domain)","HR Round"],
      aptitudePatterns: "DSA-heavy online test + basic quantitative aptitude\nFinance domain MCQs may appear\nMedium difficulty DSA problems",
      interviewPatterns: "Producer-consumer using Java threads\nDesign simple stock trading system\nCAP theorem in distributed systems\nJava multithreading and Collections\nFinancial domain basics",
      jdText: "BNY Mellon requires Java, Python, SQL, PostgreSQL, Data Structures, Algorithms, REST APIs, Spring Boot, Microservices, System Design, Git, Docker. Core banking, investment management, risk systems. Finance domain knowledge valued.",      prepTips: "Solve LeetCode Medium — focus on graphs and DP.\nStudy distributed systems basics (CAP, eventual consistency).\nLearn Spring Boot and REST API development.\nUnderstand basic financial concepts (equities, bonds).",
      tags: ["fintech","banking-domain","global-exposure","good-package"],
      companyOverview: "World's largest custodian bank. Assets under custody: $45 trillion. Revenue: $17B+. Major India tech center in Pune with 10,000+ engineers.",
      techStack: ["Java","Python","SQL","Spring Boot","AWS","Kafka","React"],
      workCulture: "Finance industry culture. Structured processes. Good work-life balance. Strong L&D. Global project exposure. Excellent benefits.",
      growthPath: "Technology Analyst → Associate → Vice President (banking titles)",
      interviewDifficulty: "Medium",
      bondDetails: "No bond.",
      hiringMode: "Campus + Online",
      testPlatform: "HackerRank",
      bond: "None",
      packageBreakdown: "Tech Analyst: ₹8 LPA, SE: ₹12–18 LPA",
    },
  ];

  await Company.insertMany(companies);
  console.log(`✅ ${companies.length} companies seeded\n`);
}
seed()
  .then(() => {
    console.log("🌱 Seeding completed");
    process.exit(0);
  })
  .catch((err) => {
    console.error("❌ Seeding error:", err);
    process.exit(1);
  });